### ISSUE TITLE
`emcc: error: no input files` when running `make all`

### ISSUE THREAD

**Issue by guizmaii** [pboutes/jq-wasm#11]
Hi @pboutes,

I was trying to compile jq to wasm with your project but when I launch `make all`, I have this issue:
```make
emcc: warning: jq.o is not a valid input file [-Winvalid-input]
emcc: error: no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.C', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.S', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.s', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')
make: *** [wasm] Error 1
```

Any idea how to fix it, maybe?

**Comment by pboutes** [comment]
Hi @guizmaii,

I had a look since I did not touch that in a while. So I saw that emscripten changes its WebAssembly backend since version `1.39.0`, and behaviors seem to be a little bit different.

So in order to get things working, I just set the docker image to what it was before (`1.38.22`). So that's not ideal, but I guess this is enough to test this POC 😄 

I tested it and that should be ok.

**Comment by guizmaii** [comment]
Thanks.

FYI, I discovered this repo: https://github.com/biowasm/biowasm, containing this: https://github.com/biowasm/biowasm/tree/main/tools/jq, which is published in their CDN: https://biowasm.com/cdn/v3

**Comment by pboutes** [comment]
Thanks @guizmaii for the info, it looks awesome!
